#!/bin/bash
#Prints to bar and sleeps

while true; do

#Battery 
STATE=`upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state| awk '{print $2}'`;
[ "$STATE" = "charging" ]&&STATE="++"||STATE="";

AUDIO=`amixer -D pulse sget Master | grep 'Left:'`;
ISMUTED=`echo $AUDIO | awk '{print $6}'`; 
[ $ISMUTED = "[off]" ] && VOLUME="Muted" || VOLUME=`echo $AUDIO | awk -F '[][]' '{ print $2 }'`; #if muted, volume 0



xsetroot -name "  |  Bat: $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | awk '{print $2}' | cut -c 1-2;) $STATE  |  Temp: $(sensors | grep -m 1 temp1 | awk '{ print $2 }')  |  Uptime: $(uptime | awk '{print $3"m"}' | tr -d ',')  |  Audio: $VOLUME  |  $(free -m | grep '^Mem' | awk '{print $3"MB"}')  |  $( date +"%F    %R  " )"
    sleep 1m
done &
